export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_FAIL = "REGISTER_FAIL" 

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_FAIL = "LOGOUT_FAIL" 

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const GUIDE_REGISTER_SUCCESS = "GUIDE_REGISTER_SUCCESS"
export const GUIDE_REGISTER_REQUEST = "GUIDE_REGISTER_REQUEST"
export const GUIDE_REGISTER_FAIL = "GUIDE_REGISTER_FAIL" 

export const GUIDE_LOGIN_SUCCESS = "GUIDE_LOGIN_SUCCESS"
export const GUIDE_LOGIN_REQUEST = "GUIDE_LOGIN_REQUEST"
export const GUIDE_LOGIN_FAIL = "GUIDE_LOGIN_FAIL" 

export const CLEAR_ERROR = "CLEAR_ERROR"